version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: coffee_dw

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: coffee123
      POSTGRES_DB: coffee_sales

    ports:
      - "5433:5432"

    volumes:
      - ./sql/dw_coffee_sales.sql:/docker-entrypoint-initdb.d/dw_coffee_sales.sql
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: